VERSION
using Pkg
using CSV, DataFrames, Conda, LinearAlgebra, Statistics
using ScikitLearn
using StatsPlots
using Plots

# 1686319/1686319 / 485631/485631 x 21 / 22 / 22 / 22
trainDf = CSV.read("F:\\UvA\\app\\trainDF_dataframeTPTNModeling_0d5FinalScoreRatio.csv", DataFrame)
trainDEDf = CSV.read("F:\\UvA\\app\\trainDF_dataframeTPTNModeling_0d5FinalScoreRatioDE.csv", DataFrame)
trainDEFDf = CSV.read("F:\\UvA\\app\\trainDF_dataframeTPTNModeling_0d5FinalScoreRatioDEFilter.csv", DataFrame)
trainDEFSDf = CSV.read("F:\\UvA\\app\\trainDF_dataframeTPTNModeling_0d5FinalScoreRatioDEFilterSTD.csv", DataFrame)

# 421381/421381 / 121946/121946 x 21 / 22 / 22 / 22
testDf = CSV.read("F:\\UvA\\app\\testDF_dataframeTPTNModeling_0d5FinalScoreRatio.csv", DataFrame)
testDEDf = CSV.read("F:\\UvA\\app\\testDF_dataframeTPTNModeling_0d5FinalScoreRatioDE.csv", DataFrame)
testDEFDf = CSV.read("F:\\UvA\\app\\testDF_dataframeTPTNModeling_0d5FinalScoreRatioDEFilter.csv", DataFrame)
testDEFSDf = CSV.read("F:\\UvA\\app\\testDF_dataframeTPTNModeling_0d5FinalScoreRatioDEFilterSTD.csv", DataFrame)

# 10908/10908 / 10868/10868 x 18 / 19 / 19 / 19
noTeaDf = CSV.read("F:\\UvA\\app\\noTeaDF_dataframeTPTNModeling_0d5FinalScoreRatio.csv", DataFrame)
noTeaDEDf = CSV.read("F:\\UvA\\app\\noTeaDF_dataframeTPTNModeling_0d5FinalScoreRatioDE.csv", DataFrame)
noTeaDEFDf = CSV.read("F:\\UvA\\app\\noTeaDF_dataframeTPTNModeling_0d5FinalScoreRatioDEFilter.csv", DataFrame)
noTeaDEFSDf = CSV.read("F:\\UvA\\app\\noTeaDF_dataframeTPTNModeling_0d5FinalScoreRatioDEFilterSTD.csv", DataFrame)

# 29599/29599 / 29397/29397 x 18 / 19 / 19 / 19
TeaDf = CSV.read("F:\\UvA\\app\\TeaDF_dataframeTPTNModeling_0d5FinalScoreRatio.csv", DataFrame)
TeaDEDf = CSV.read("F:\\UvA\\app\\TeaDF_dataframeTPTNModeling_0d5FinalScoreRatioDE.csv", DataFrame)
TeaDEFDf = CSV.read("F:\\UvA\\app\\TeaDF_dataframeTPTNModeling_0d5FinalScoreRatioDEFilter.csv", DataFrame)
TeaDEFSDf = CSV.read("F:\\UvA\\app\\TeaDF_dataframeTPTNModeling_0d5FinalScoreRatioDEFilterSTD.csv", DataFrame)

describe(trainDf)[5:14, :]
describe(TeaDEFDf)[5:14, :]
describe(TeaDf)[5:14, :]
describe(TeaDEFDf)[5:14, :]
# ==================================================================================================

trainDf_0 = trainDf[trainDf.LABEL .== 0, :]
trainDf_1 = trainDf[trainDf.LABEL .== 1, :]
testDf_0 = testDf[testDf.LABEL .== 0, :]
testDf_1 = testDf[testDf.LABEL .== 1, :]
noTeaDf_0 = noTeaDf[noTeaDf.LABEL .== 0, :]
noTeaDf_1 = noTeaDf[noTeaDf.LABEL .== 1, :]
TeaDf_1 = TeaDf[TeaDf.LABEL .== 1, :]

trainDEDf_0 = trainDEDf[trainDEDf.LABEL .== 0, :]
trainDEDf_1 = trainDEDf[trainDEDf.LABEL .== 1, :]
testDEDf_0 = testDEDf[testDEDf.LABEL .== 0, :]
testDEDf_1 = testDEDf[testDEDf.LABEL .== 1, :]
noTeaDEDf_0 = noTeaDEDf[noTeaDEDf.LABEL .== 0, :]
noTeaDEDf_1 = noTeaDEDf[noTeaDEDf.LABEL .== 1, :]
TeaDEDf_1 = TeaDEDf[TeaDEDf.LABEL .== 1, :]

trainDEFDf_0 = trainDEFDf[trainDEFDf.LABEL .== 0, :]
trainDEFDf_1 = trainDEFDf[trainDEFDf.LABEL .== 1, :]
testDEFDf_0 = testDEFDf[testDEFDf.LABEL .== 0, :]
testDEFDf_1 = testDEFDf[testDEFDf.LABEL .== 1, :]
noTeaDEFDf_0 = noTeaDEFDf[noTeaDEFDf.LABEL .== 0, :]
noTeaDEFDf_1 = noTeaDEFDf[noTeaDEFDf.LABEL .== 1, :]
TeaDEFDf_1 = TeaDEFDf[TeaDEFDf.LABEL .== 1, :]

trainDEFSDf_0 = trainDEFSDf[trainDEFSDf.LABEL .== 0, :]
trainDEFSDf_1 = trainDEFSDf[trainDEFSDf.LABEL .== 1, :]
testDEFSDf_0 = testDEFSDf[testDEFSDf.LABEL .== 0, :]
testDEFSDf_1 = testDEFSDf[testDEFSDf.LABEL .== 1, :]
noTeaDEFSDf_0 = noTeaDEFSDf[noTeaDEFSDf.LABEL .== 0, :]
noTeaDEFSDf_1 = noTeaDEFSDf[noTeaDEFSDf.LABEL .== 1, :]
TeaDEFSDf_1 = TeaDEFSDf[TeaDEFSDf.LABEL .== 1, :]
# ==================================================================================================

using DataSci4Chem

layout = @layout [a{0.25w,0.25h} b{0.25w,0.25h} c{0.25w,0.25h} d{0.25w,0.25h} 
                  e{0.25w,0.25h} f{0.25w,0.25h} g{0.25w,0.25h} h{0.25w,0.25h} 
                  i{0.25w,0.25h} j{0.25w,0.25h} k{0.25w,0.25h} l{0.25w,0.25h} 
                  m{0.25w,0.25h} n{0.25w,0.25h} o{0.25w,0.25h} p{0.25w,0.25h} ]
default(grid = false, legend = false)
gr()

outplotTPTNdetaRiDistrution = plot(layout = layout, link = :both, 
        size = (1500, 1500), margin = (8, :mm), dpi = 300)

histogram!(trainDf_0[:, "DirectMatch"], bins = 150, 
    subplot = 1, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
    histogram!(trainDf_1[:, "DirectMatch"], bins = 150, 
    subplot = 1, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf_0[:, "DirectMatch"], bins = 150, 
    subplot = 5, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
    histogram!(testDf_1[:, "DirectMatch"], bins = 150, 
    subplot = 5, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(noTeaDf_0[:, "DirectMatch"], bins = 150, 
    subplot = 9, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Validation Dataset", 
    titlefont = font(12), 
    dpi = 300)
    histogram!(noTeaDf_1[:, "DirectMatch"], bins = 150, 
    subplot = 9, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Validation Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(TeaDf_1[:, "DirectMatch"], bins = 150, 
    subplot = 13, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Real Sample Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDEDf_0[:, "ReversMatch"], bins = 150, 
    subplot = 2, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
    histogram!(trainDEDf_1[:, "ReversMatch"], bins = 150, 
    subplot = 2, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDEDf_0[:, "ReversMatch"], bins = 150, 
    subplot = 6, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
    histogram!(testDEDf_1[:, "ReversMatch"], bins = 150, 
    subplot = 6, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(noTeaDEDf_0[:, "ReversMatch"], bins = 150, 
    subplot = 10, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Validation Dataset", 
    titlefont = font(12), 
    dpi = 300)
    histogram!(noTeaDEDf_1[:, "ReversMatch"], bins = 150, 
    subplot = 10, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Validation Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(TeaDEDf_1[:, "ReversMatch"], bins = 150, 
    subplot = 14, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Real Sample Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDEFDf_0[:, "MatchDiff"], bins = 150, 
    subplot = 3, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff\n= DirectMatch - ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Scaled\nTraining Dataset", 
    titlefont = font(12), 
    dpi = 300)
    histogram!(trainDEFDf_1[:, "MatchDiff"], bins = 150, 
    subplot = 3, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff\n= DirectMatch - ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Scaled\nTraining Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDEFDf_0[:, "MatchDiff"], bins = 150, 
    subplot = 7, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff\n= DirectMatch - ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Scaled\nTesting Dataset", 
    titlefont = font(12), 
    dpi = 300)
    histogram!(testDEFDf_1[:, "MatchDiff"], bins = 150, 
    subplot = 7, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff\n= DirectMatch - ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Scaled\nTesting Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(noTeaDEFDf_0[:, "MatchDiff"], bins = 150, 
    subplot = 11, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff\n= DirectMatch - ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Scaled\nValidation Dataset", 
    titlefont = font(12), 
    dpi = 300)
    histogram!(noTeaDEFDf_1[:, "MatchDiff"], bins = 150, 
    subplot = 11, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff\n= DirectMatch - ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Scaled\nValidation Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(TeaDEFDf_1[:, "MatchDiff"], bins = 150, 
    subplot = 15, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff\n= DirectMatch - ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Scaled\nReal Sample Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDEFSDf_0[:, "MatchDiff"], bins = 150, 
    subplot = 4, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "z-score of MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Standardized\nTraining Dataset", 
    titlefont = font(12), 
    dpi = 300)
    histogram!(trainDEFSDf_1[:, "MatchDiff"], bins = 150, 
    subplot = 4, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "z-score of MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Standardized\nTraining Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDEFSDf_0[:, "MatchDiff"], bins = 150, 
    subplot = 8, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "z-score of MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Standardized\nTesting Dataset", 
    titlefont = font(12), 
    dpi = 300)
    histogram!(testDEFSDf_1[:, "MatchDiff"], bins = 150, 
    subplot = 8, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "z-score of MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Standardized\nTesting Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(noTeaDEFSDf_0[:, "MatchDiff"], bins = 150, 
    subplot = 12, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "z-score of MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Standardized\nValidation Dataset", 
    titlefont = font(12), 
    dpi = 300)
    histogram!(noTeaDEFSDf_1[:, "MatchDiff"], bins = 150, 
    subplot = 12, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "z-score of MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Standardized\nValidation Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(TeaDEFSDf_1[:, "MatchDiff"], bins = 150, 
    subplot = 16, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "z-score of MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Standardized\nReal Sample Dataset", 
    titlefont = font(12), 
    dpi = 300)


# Saving
savefig(outplotTPTNdetaRiDistrution, "F:\\UvA\\app\\outplot_TPTNDistrution_FeatureMatch.png")
