VERSION
using Pkg
using CSV, DataFrames, Conda, LinearAlgebra, Statistics
using ScikitLearn
using StatsPlots
using Plots

# 4103848 x 4 + 8 + 1 + 2 + 1 + 1
trainDf = CSV.read("F:\\UvA\\dataframeTPTNModeling_TrainDFwithhl0d5FinalScoreRatio2.csv", DataFrame)
trainDf2 = CSV.read("F:\\UvA\\dataframeTPTNModeling_TrainDFwithhl0d5FinalScoreRatio2Filter.csv", DataFrame)
trainDEDf = CSV.read("F:\\UvA\\dataframeTPTNModeling_TrainDFwithhl0d5FinalScoreRatio2DE.csv", DataFrame)
trainDEDf2 = CSV.read("F:\\UvA\\dataframeTPTNModeling_TrainDFwithhl0d5FinalScoreRatio2DE2Filter.csv", DataFrame)

testDf = CSV.read("F:\\UvA\\dataframeTPTNModeling_TestDFwithhl0d5FinalScoreRatio2.csv", DataFrame)
testDf2 = CSV.read("F:\\UvA\\dataframeTPTNModeling_TestDFwithhl0d5FinalScoreRatio2Filter.csv", DataFrame)
testDEDf = CSV.read("F:\\UvA\\dataframeTPTNModeling_TestDFwithhl0d5FinalScoreRatio2DE.csv", DataFrame)
testDEDf2 = CSV.read("F:\\UvA\\dataframeTPTNModeling_TestDFwithhl0d5FinalScoreRatio2DE2Filter.csv", DataFrame)

pestDf = CSV.read("F:\\UvA\\dataframeTPTNModeling_pestDFwithhl0d5FinalScoreRatio2.csv", DataFrame)
pestDf2 = CSV.read("F:\\UvA\\dataframeTPTNModeling_pestDFwithhl0d5FinalScoreRatio2Filter.csv", DataFrame)
pestDEDf = CSV.read("F:\\UvA\\dataframeTPTNModeling_pestDFwithhl0d5FinalScore2RatioDE.csv", DataFrame)
pestDEDf2 = CSV.read("F:\\UvA\\dataframeTPTNModeling_pestDFwithhl0d5FinalScore2RatioDE2Filter.csv", DataFrame)

describe(trainDf)[1:end, :]
describe(testDf)[1:end, :]
describe(pestDf_DE1)[1:end, :]
# ==================================================================================================

trainDf_0 = trainDf[trainDf.LABEL .== 0, :]
trainDf_1 = trainDf[trainDf.LABEL .== 1, :]
testDf_0 = testDf[testDf.LABEL .== 0, :]
testDf_1 = testDf[testDf.LABEL .== 1, :]
pestDf_0 = pestDf[pestDf.LABEL .== 0, :]
pestDf_1 = pestDf[pestDf.LABEL .== 1, :]

trainDf2_0 = trainDf2[trainDf2.LABEL .== 0, :]
trainDf2_1 = trainDf2[trainDf2.LABEL .== 1, :]
testDf2_0 = testDf2[testDf2.LABEL .== 0, :]
testDf2_1 = testDf2[testDf2.LABEL .== 1, :]
pestDf2_0 = pestDf2[pestDf2.LABEL .== 0, :]
pestDf2_1 = pestDf2[pestDf2.LABEL .== 1, :]

trainDf_DE0 = trainDEDf[trainDEDf.LABEL .== 0, :]
trainDf_DE1 = trainDEDf[trainDEDf.LABEL .== 1, :]
testDf_DE0 = testDEDf[testDEDf.LABEL .== 0, :]
testDf_DE1 = testDEDf[testDEDf.LABEL .== 1, :]
pestDf_DE0 = pestDEDf[pestDEDf.LABEL .== 0, :]
pestDf_DE1 = pestDEDf[pestDEDf.LABEL .== 1, :]

trainDf2_DE0 = trainDEDf2[trainDEDf2.LABEL .== 0, :]
trainDf2_DE1 = trainDEDf2[trainDEDf2.LABEL .== 1, :]
testDf2_DE0 = testDEDf2[testDEDf2.LABEL .== 0, :]
testDf2_DE1 = testDEDf2[testDEDf2.LABEL .== 1, :]
pestDf2_DE0 = pestDEDf2[pestDEDf2.LABEL .== 0, :]
pestDf2_DE1 = pestDEDf2[pestDEDf2.LABEL .== 1, :]
# ==================================================================================================

using DataSci4Chem

layout = @layout [a{0.50w,0.16h} b{0.50w,0.16h} 
                  c{0.50w,0.16h} d{0.50w,0.16h} 
                  e{0.50w,0.16h} f{0.50w,0.16h} 
                  g{0.50w,0.16h} h{0.50w,0.16h} 
                  i{0.50w,0.16h} j{0.50w,0.16h} 
                  k{0.50w,0.16h} l{0.50w,0.16h}]
default(grid = false, legend = false)
gr()

outplotTPTNdetaRiDistrution = plot(layout = layout, link = :both, 
        size = (1500, 1500), margin = (8, :mm), dpi = 300)

histogram!(trainDf_0[:, "FinalScoreRatio"], bins = 150, 
    subplot = 1, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "FinalScoreRatio", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf_1[:, "FinalScoreRatio"], bins = 150, 
    subplot = 1, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "FinalScoreRatio", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDf_DE0[:, "FinalScoreRatio"], bins = 150, 
    subplot = 2, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "log(FinalScoreRatio)", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Preprocessed Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf_DE1[:, "FinalScoreRatio"], bins = 150, 
    subplot = 2, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "log(FinalScoreRatio)", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Preprocessed Training Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDf2_0[:, "FinalScoreRatio"], bins = 150, 
    subplot = 3, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "FinalScoreRatio", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf2_1[:, "FinalScoreRatio"], bins = 150, 
    subplot = 3, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "FinalScoreRatio", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Training Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDf2_DE0[:, "FinalScoreRatio"], bins = 150, 
    subplot = 4, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "log(FinalScoreRatio)", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Preprocessed Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf2_DE1[:, "FinalScoreRatio"], bins = 150, 
    subplot = 4, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "log(FinalScoreRatio)", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Preprocessed Training Dataset", 
    titlefont = font(12), 
    dpi = 300)


histogram!(testDf_0[:, "FinalScoreRatio"], bins = 150, 
    subplot = 5, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "FinalScoreRatio", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf_1[:, "FinalScoreRatio"], bins = 150, 
    subplot = 5, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "FinalScoreRatio", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf_DE0[:, "FinalScoreRatio"], bins = 150, 
    subplot = 6, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "log(FinalScoreRatio)", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Preprocessed Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf_DE1[:, "FinalScoreRatio"], bins = 150, 
    subplot = 6, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "log(FinalScoreRatio)", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Preprocessed Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf2_0[:, "FinalScoreRatio"], bins = 150, 
    subplot = 7, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "FinalScoreRatio", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf2_1[:, "FinalScoreRatio"], bins = 150, 
    subplot = 7, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "FinalScoreRatio", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf2_DE0[:, "FinalScoreRatio"], bins = 150, 
    subplot = 8, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "log(FinalScoreRatio)", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Preprocessed Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf2_DE1[:, "FinalScoreRatio"], bins = 150, 
    subplot = 8, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "log(FinalScoreRatio)", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Preprocessed Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)


histogram!(pestDf_0[:, "FinalScoreRatio"], bins = 150, 
    subplot = 9, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "FinalScoreRatio", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf_1[:, "FinalScoreRatio"], bins = 150, 
    subplot = 9, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "FinalScoreRatio", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(pestDf_DE0[:, "FinalScoreRatio"], bins = 150, 
    subplot = 10, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "log(FinalScoreRatio)", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Preprocessed External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf_DE1[:, "FinalScoreRatio"], bins = 150, 
    subplot = 10, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "log(FinalScoreRatio)", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Preprocessed External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(pestDf2_1[:, "FinalScoreRatio"], bins = 150, 
    subplot = 11, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "FinalScoreRatio", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf2_0[:, "FinalScoreRatio"], bins = 150, 
    subplot = 11, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "FinalScoreRatio", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(pestDf2_DE1[:, "FinalScoreRatio"], bins = 150, 
    subplot = 12, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "log(FinalScoreRatio)", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Preprocessed External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf2_DE0[:, "FinalScoreRatio"], bins = 150, 
    subplot = 12, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "log(FinalScoreRatio)", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Preprocessed External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

# Saving
savefig(outplotTPTNdetaRiDistrution, "F:\\UvA\\outplot_TPTNDistrution_FinalScoreRatio3.png")

# ==================================================================================================

layout = @layout [a{0.50w,0.16h} b{0.50w,0.16h} 
                  c{0.50w,0.16h} d{0.50w,0.16h} 
                  e{0.50w,0.16h} f{0.50w,0.16h} 
                  g{0.50w,0.16h} h{0.50w,0.16h} 
                  i{0.50w,0.16h} j{0.50w,0.16h} 
                  k{0.50w,0.16h} l{0.50w,0.16h}]
default(grid = false, legend = false)
gr()

outplotTPTNdetaRiDistrution = plot(layout = layout, link = :both, 
        size = (1500, 1500), margin = (8, :mm), dpi = 300)

histogram!(trainDf_0[:, "DeltaRi"], bins = 150, 
    subplot = 1, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "1-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Preprocessed Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf_1[:, "DeltaRi"], bins = 150, 
    subplot = 1, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "1-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Preprocessed Training Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDf_DE0[:, "DeltaRi"], bins = 150, 
    subplot = 2, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "2-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf_DE1[:, "DeltaRi"], bins = 150, 
    subplot = 2, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "2-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDf2_0[:, "DeltaRi"], bins = 150, 
    subplot = 3, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "1-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Preprocessed Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf2_1[:, "DeltaRi"], bins = 150, 
    subplot = 3, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "1-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Preprocessed Training Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDf2_DE0[:, "DeltaRi"], bins = 150, 
    subplot = 4, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "2-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf2_DE1[:, "DeltaRi"], bins = 150, 
    subplot = 4, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "2-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Training Dataset", 
    titlefont = font(12), 
    dpi = 300)


histogram!(testDf_0[:, "DeltaRi"], bins = 150, 
    subplot = 5, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "1-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Preprocessed Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf_1[:, "DeltaRi"], bins = 150, 
    subplot = 5, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "1-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Preprocessed Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf_DE0[:, "DeltaRi"], bins = 150, 
    subplot = 6, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "2-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf_DE1[:, "DeltaRi"], bins = 150, 
    subplot = 6, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "2-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf2_0[:, "DeltaRi"], bins = 150, 
    subplot = 7, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "1-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Preprocessed Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf2_1[:, "DeltaRi"], bins = 150, 
    subplot = 7, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "1-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Preprocessed Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf2_DE0[:, "DeltaRi"], bins = 150, 
    subplot = 8, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "2-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf2_DE1[:, "DeltaRi"], bins = 150, 
    subplot = 8, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "2-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)


histogram!(pestDf_0[:, "DeltaRi"], bins = 150, 
    subplot = 9, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "1-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Preprocessed External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf_1[:, "DeltaRi"], bins = 150, 
    subplot = 9, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "1-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Preprocessed External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(pestDf_DE0[:, "DeltaRi"], bins = 150, 
    subplot = 10, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "2-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf_DE1[:, "DeltaRi"], bins = 150, 
    subplot = 10, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "2-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(pestDf2_1[:, "DeltaRi"], bins = 150, 
    subplot = 11, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "1-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Preprocessed External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf2_0[:, "DeltaRi"], bins = 150, 
    subplot = 11, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "1-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Preprocessed External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(pestDf2_DE1[:, "DeltaRi"], bins = 150, 
    subplot = 12, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "2-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf2_DE0[:, "DeltaRi"], bins = 150, 
    subplot = 12, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "2-Way DeltaRI", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

# Saving
savefig(outplotTPTNdetaRiDistrution, "F:\\UvA\\outplot_TPTNDistrution_DeltaRI3.png")

# ==================================================================================================

layout = @layout [a{0.50w,0.16h} b{0.50w,0.16h} 
                  c{0.50w,0.16h} d{0.50w,0.16h} 
                  e{0.50w,0.16h} f{0.50w,0.16h} 
                  g{0.50w,0.16h} h{0.50w,0.16h} 
                  i{0.50w,0.16h} j{0.50w,0.16h} 
                  k{0.50w,0.16h} l{0.50w,0.16h}]
default(grid = false, legend = false)
gr()

outplotTPTNdetaRiDistrution = plot(layout = layout, link = :both, 
        size = (1500, 1500), margin = (8, :mm), dpi = 300)

histogram!(trainDf_DE0[:, "MS2Error"], bins = 150, 
    subplot = 1, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2Error", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf_DE1[:, "MS2Error"], bins = 150, 
    subplot = 1, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2Error", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDf_DE0[:, "MS2ErrorStd"], bins = 150, 
    subplot = 2, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2ErrorStd", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf_DE1[:, "MS2ErrorStd"], bins = 150, 
    subplot = 2, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2ErrorStd", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDf2_DE0[:, "MS2Error"], bins = 150, 
    subplot = 3, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2Error", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf2_DE1[:, "MS2Error"], bins = 150, 
    subplot = 3, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2Error", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Training Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDf2_DE0[:, "MS2ErrorStd"], bins = 150, 
    subplot = 4, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2ErrorStd", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf2_DE1[:, "MS2ErrorStd"], bins = 150, 
    subplot = 4, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2ErrorStd", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Training Dataset", 
    titlefont = font(12), 
    dpi = 300)


histogram!(testDf_DE0[:, "MS2Error"], bins = 150, 
    subplot = 5, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2Error", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf_DE1[:, "MS2Error"], bins = 150, 
    subplot = 5, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2Error", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf_DE0[:, "MS2ErrorStd"], bins = 150, 
    subplot = 6, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2ErrorStd", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf_DE1[:, "MS2ErrorStd"], bins = 150, 
    subplot = 6, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2ErrorStd", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf2_DE0[:, "MS2Error"], bins = 150, 
    subplot = 7, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2Error", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf2_DE1[:, "MS2Error"], bins = 150, 
    subplot = 7, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2Error", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf2_DE0[:, "MS2ErrorStd"], bins = 150, 
    subplot = 8, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2ErrorStd", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf2_DE1[:, "MS2ErrorStd"], bins = 150, 
    subplot = 8, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2ErrorStd", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)


histogram!(pestDf_DE0[:, "MS2Error"], bins = 150, 
    subplot = 9, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2Error", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf_DE1[:, "MS2Error"], bins = 150, 
    subplot = 9, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2Error", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(pestDf_DE0[:, "MS2ErrorStd"], bins = 150, 
    subplot = 10, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2ErrorStd", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf_DE1[:, "MS2ErrorStd"], bins = 150, 
    subplot = 10, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2ErrorStd", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(pestDf2_DE1[:, "MS2Error"], bins = 150, 
    subplot = 11, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2Error", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf2_DE0[:, "MS2Error"], bins = 150, 
    subplot = 11, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2Error", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(pestDf2_DE1[:, "MS2ErrorStd"], bins = 150, 
    subplot = 12, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2ErrorStd", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf2_DE0[:, "MS2ErrorStd"], bins = 150, 
    subplot = 12, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MS2ErrorStd", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topright, 
    legendfont = font(8), 
    title = "Filtered External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

# Saving
savefig(outplotTPTNdetaRiDistrution, "F:\\UvA\\outplot_TPTNDistrution_MS2ErrorNStd3.png")

# ==================================================================================================

layout = @layout [a{0.33w,0.16h} b{0.33w,0.16h} c{0.33w,0.16h} 
                  d{0.33w,0.16h} e{0.33w,0.16h} f{0.33w,0.16h} 
                  g{0.33w,0.16h} h{0.33w,0.16h} i{0.33w,0.16h} 
                  j{0.33w,0.16h} k{0.33w,0.16h} l{0.33w,0.16h}
                  m{0.33w,0.16h} n{0.33w,0.16h} o{0.33w,0.16h} 
                  p{0.33w,0.16h} q{0.33w,0.16h} r{0.33w,0.16h}]
default(grid = false, legend = false)
gr()

outplotTPTNdetaRiDistrution = plot(layout = layout, link = :both, 
        size = (1500, 1500), margin = (8, :mm), dpi = 300)

histogram!(trainDf_0[:, "DirectMatch"], bins = 150, 
    subplot = 1, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf_1[:, "DirectMatch"], bins = 150, 
    subplot = 1, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDf_0[:, "ReversMatch"], bins = 150, 
    subplot = 2, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf_1[:, "ReversMatch"], bins = 150, 
    subplot = 2, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Training Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDf_DE0[:, "MatchRatio"], bins = 150, 
    subplot = 3, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Preprocessed Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf_DE1[:, "MatchRatio"], bins = 150, 
    subplot = 3, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Preprocessed Training Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDf2_0[:, "DirectMatch"], bins = 150, 
    subplot = 4, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf2_1[:, "DirectMatch"], bins = 150, 
    subplot = 4, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Training Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDf2_0[:, "ReversMatch"], bins = 150, 
    subplot = 5, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf2_1[:, "ReversMatch"], bins = 150, 
    subplot = 5, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Training Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(trainDf2_DE0[:, "MatchRatio"], bins = 150, 
    subplot = 6, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Preprocessed Training Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(trainDf2_DE1[:, "MatchRatio"], bins = 150, 
    subplot = 6, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Preprocessed Training Dataset", 
    titlefont = font(12), 
    dpi = 300)


histogram!(testDf_0[:, "DirectMatch"], bins = 150, 
    subplot = 7, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf_1[:, "DirectMatch"], bins = 150, 
    subplot = 7, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf_0[:, "ReversMatch"], bins = 150, 
    subplot = 8, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf_1[:, "ReversMatch"], bins = 150, 
    subplot = 8, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf_DE0[:, "MatchRatio"], bins = 150, 
    subplot = 9, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Preprocessed Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf_DE1[:, "MatchRatio"], bins = 150, 
    subplot = 9, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Preprocessed Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf2_0[:, "DirectMatch"], bins = 150, 
    subplot = 10, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf2_1[:, "DirectMatch"], bins = 150, 
    subplot = 10, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf2_0[:, "ReversMatch"], bins = 150, 
    subplot = 11, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf2_1[:, "ReversMatch"], bins = 150, 
    subplot = 11, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf2_DE0[:, "MatchRatio"], bins = 150, 
    subplot = 12, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf2_DE1[:, "MatchRatio"], bins = 150, 
    subplot = 12, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Preprocessed Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)


histogram!(pestDf_0[:, "DirectMatch"], bins = 150, 
    subplot = 13, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf_1[:, "DirectMatch"], bins = 150, 
    subplot = 13, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(pestDf_0[:, "ReversMatch"], bins = 150, 
    subplot = 14, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf_1[:, "ReversMatch"], bins = 150, 
    subplot = 14, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(pestDf_DE0[:, "MatchRatio"], bins = 150, 
    subplot = 15, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Preprocessed External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf_DE1[:, "MatchRatio"], bins = 150, 
    subplot = 15, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Preprocessed External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(pestDf2_1[:, "DirectMatch"], bins = 150, 
    subplot = 16, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf2_0[:, "DirectMatch"], bins = 150, 
    subplot = 16, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "DirectMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf2_1[:, "ReversMatch"], bins = 150, 
    subplot = 17, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(pestDf2_DE0[:, "ReversMatch"], bins = 150, 
    subplot = 17, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "ReverseMatch", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)

histogram!(testDf2_DE0[:, "MatchRatio"], bins = 150, 
    subplot = 18, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 0", 
    fc = "pink", 
    lc = "pink", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered External Independent Dataset", 
    titlefont = font(12), 
    dpi = 300)
histogram!(testDf2_DE1[:, "MatchRatio"], bins = 150, 
    subplot = 18, 
    framestyle = :box, 
    seriestype=:stephist, 
    xlabel = "MatchDiff", xguidefontsize=10, 
    ylabel = "Count", yguidefontsize=10, 
    label = "LABEL 1", 
    fc = "skyblue", 
    lc = "skyblue", 
    lw = 1, 
    margin = (5, :mm), 
    xtickfontsize = 8, 
    ytickfontsize= 8, 
    legend = :topleft, 
    legendfont = font(8), 
    title = "Filtered Preprocessed Testing Dataset", 
    titlefont = font(12), 
    dpi = 300)

# Saving
savefig(outplotTPTNdetaRiDistrution, "F:\\UvA\\outplot_TPTNDistrution_Match3.png")
